version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  prod:
    build: .
    volumes:
      - .:/chefs_office_working
      - public-data:/chefs_office_working/public
      - tmp-data:/chefs_office_working/tmp
      - log-data:/chefs_office_working/log
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  nginx:
    build:
      context: containers/nginx
    volumes:
      - public-data:/chefs_office_working/public
      - tmp-data:/chefs_office_working/tmp
    ports:
      - 80:80
    depends_on:
      - prod
volumes:
  mysql-data:
    driver: local
  public-data:
  tmp-data:
  log-data:
  db-data: